eureka:
  instance: 
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 10
    metadataMap:
      providerName: Joerg
      payment: perCall
      instanceId: JoergBakery1
  client:
    fetchRegistry: false
    instanceInfoReplicationIntervalSeconds: 10
    initialInstanceInfoReplicationIntervalSeconds: 10
    serviceUrl:
      defaultZone: https://eurekas.onevoila.rocks/eureka
      
